const actionTypes = {
  FETCH_MOVIES_DATA_REQUEST: `FETCH_MOVIES_DATA_REQUEST`,
  FETCH_MOVIES_DATA_SUCCESS: `FETCH_MOVIES_DATA_SUCCESS`,
  FETCH_MOVIES_DATA_ERROR: `FETCH_MOVIES_DATA_ERROR`,
  CHANGE_ACTIVE_GENRE: `CHANGE_ACTIVE_GENRE`,
  CHANGE_MOVIES_LIMIT: `CHANGE_MOVIES_LIMIT`,
  RESET_MOVIES_LIMIT: `RESET_MOVIES_LIMIT`,
  SET_AUTH: `SET_AUTH`,
  AUTHORIZE_USER: `AUTHORIZE_USER`,
  LOGIN_REQUEST: `LOGIN_REQUEST`,
  LOGIN_SUCCESS: `LOGIN_SUCCESS`,
  LOGIN_ERROR: `LOGIN_ERROR`,
};

export {actionTypes};
