const actionTypes = {
  FETCH_MOVIES_DATA_REQUEST: `FETCH_MOVIES_DATA_REQUEST`,
  FETCH_MOVIES_DATA_SUCCESS: `FETCH_MOVIES_DATA_SUCCESS`,
  FETCH_MOVIES_DATA_ERROR: `FETCH_MOVIES_DATA_ERROR`,
};

export {actionTypes};
